FROM golang:1.18-alpine as build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download
ADD . .
RUN go build -o /gte-daemon ./cmd/daemon/service.go

FROM alpine:latest

RUN apk add ca-certificates
COPY --from=build /gte-daemon /gte-daemon
CMD ["/gte-daemon"]
