# fly.toml file generated for gte-daemon on 2022-09-14T15:53:30+02:00

app = "gte-daemon"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile.daemon"

[env]
  IMAP_URL = "imap.fastmail.com:993"
  IMAP_FOLDER_PREFIX = "GTE/"
  SMTP_URL = "smtp.fastmail.com:465"
  GTE_TO_NAME = "gte"
  GTE_FROM_NAME = "gte"
  GTE_DAYS_AHEAD = 6

[experimental]
  allowed_public_ports = []
  auto_rollback = true

